name = "api-badbunnyconcertecuador"
workers_dev = true
compatibility_date = "2022-05-28"
main = "dist/worker.js"

kv_namespaces = [
  { binding = "BadbunnyConcertEcuador", id = "b18d4160eb774b0ca660b04b721dd283" }
]

[build]
command = "yarn install && yarn run build"
