name = "tweets-deploy"
compatibility_date = "2022-08-08"
main = "src/index.ts"
workers_dev = false

services = [
  { binding = "tweets", service = "tweets-service", environment = "production"}
]

[triggers]
crons = [ "0 12 * * *" ]
