name = "films-service"
type = "javascript"
route = "api.yoshualopez.com/films"
workers_dev = true
compatibility_date = "2021-10-15"

[build]
command = "yarn install && yarn run build"
[build.upload]
format = "service-worker"
