name = "honeygain"
type = "javascript"
compatibility_date = "2022-01-10"

[triggers]
crons = ["10 18 * * *"]

[build]
command = "yarn install && yarn run build"
[build.upload]
format = "service-worker"
